# Generated by Django 3.2.12 on 2022-04-10 11:01

import Calories.usersapp.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('time', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('calories', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='', validators=[Calories.usersapp.validators.image_max_size])),
                ('date_of_input', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('weight', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('calories', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='', validators=[Calories.usersapp.validators.image_max_size])),
                ('date_of_input', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('weight', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('calories', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='', validators=[Calories.usersapp.validators.image_max_size])),
                ('date_of_input', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
