# Generated by Django 3.2.12 on 2022-04-11 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='calories',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='activities',
            name='time',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='calories',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='meals',
            name='calories',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='meals',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
